trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  group: 'bookings-app'

steps:

- script: echo $(location)

- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  displayName: Build Application
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:outDir="$(build.artifactStagingDirectory)\WebApp" /p:Configuration=Release'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: ArchiveFiles@2
  displayName: Create Artifact
  inputs:
    rootFolderOrFile: '$(build.artifactStagingDirectory)\WebApp\_PublishedWebsites\MSDTCApp'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(build.artifactStagingDirectory)\WebApp.zip' 
    replaceExistingArchive: true 

- task: AzureFileCopy@4
  displayName: Publishing Artifact
  inputs:
    sourcePath: '$(build.artifactStagingDirectory)/WebApp.zip'
    azureSubscription: service-connection
    destination: azureBlob
    storage: '$(artifactStorageAccount)'
    containerName: '$(artifactContainer)'

- task: AzureCLI@2
  displayName: Build VM Image
  inputs:
    azureSubscription: service-connection
    scriptType: ps
    scriptLocation: inlineScript
    inlineScript: |
      Write-Host "Deploying Image Template"
      az deployment group create --resource-group $(resourceGroup) --template-file bookings-app-vm-template.json --parameters location=$(location) name=bookings-app-$(Build.BuildNumber) identity=$(managedIdentity) sqlmi_dns_suffix=$(sqlDnsSuffix) artifact_storage_account=$(artifactStorageAccount) artifact_container=$(artifactContainer)
      Write-Host "Building VM Image"
      az resource invoke-action --resource-group fleetcor --resource-type Microsoft.VirtualMachineImages/imageTemplates -n bookings-app-$(Build.BuildNumber) --action Run